### ISSUE TITLE
invitation to participate in authoring the CIS benachmark

### ISSUE THREAD

**Issue by hunleyd** [HexaCluster/pgdsat#7]
As the primary contributor to the CIS benchmarks for PG, I'd first like to say 'great job on this tool' and then I'd like to invite you to join CIS and help me improve the benchmarks. Right now, it's just little ole me, and I could certainly use the help. I'd also be interested in seeing you contribute any additional checks back into the benchmark for everyone's benefit. 
Thanks and keep up the great work!

**Comment by darold** [comment]
Hello,

Thanks you a lot for the encouragement and making contact.I was just looking to see if it was possible to participate in improving the Benchmark with the new checks we have though about so that we have a common reference. My idea while implementing this tool is that the CIS Benchmark for PostgreSQL and pgdsat are permanently very close so that there is a reference or standardization in terms of security policies check for PostgreSQL.

You can contact me on my private email gilles@darold.net to talk about the detail on the way to contribute to CIS Benchmark and how we will work together.

Thank you again, without your great work on PostgreSQL CIS Benchmark this tool would have been more complicated to implement.
